version: "3.9"
services:
  mongodbcontainer:
    image: mongo:latest
    container_name: mongodbcontainer
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpwd
    volumes:
      - ${MONGO_HOST_DATA}/db:/data/db
    ports:
      - 27018:27017
    restart: always
    logging:
      options:
        max-size: 1g
    networks:
      - btc39-net
  ms-configserver:
    build: ./ms_configserver
    container_name: ms-configserver
    ports:
      - "8888:8888"
    networks:
      - btc39-net
  ms-discoveryserver:
    build: ./ms_discoveryserver
    container_name: ms-discoveryserver
    ports:
      - "8761:8761"
    networks:
      - btc39-net
  ms-product:
    build: ./ms_product
    container_name: ms-product
    ports:
      - "8081:8081"
    links:
      - mongodbcontainer
    depends_on:
      - ms-configserver
      - ms-discoveryserver
      - mongodbcontainer
    networks:
      - btc39-net
  ms-client:
    build: ./ms_client
    container_name: ms-client
    ports:
      - "8082:8082"
    links:
      - mongodbcontainer
    depends_on:
      - ms-configserver
      - ms-discoveryserver
      - mongodbcontainer
    networks:
      - btc39-net
  ms-gateway:
    build: ./ms_gateway
    container_name: ms-gateway
    ports:
      - "8080:8080"
    depends_on:
      - ms-configserver
      - ms-discoveryserver
      - ms-product
      - ms-client
    networks:
      - btc39-net
  ms-pasivoahorro:
    build: ./ms_pasivoahorro
    container_name: ms-pasivoahorro
    ports:
      - "8084:8084"
    links:
      - mongodbcontainer
    depends_on:
      - ms-configserver
      - ms-discoveryserver
      - ms-client
      - ms-product
      - mongodbcontainer
    networks:
      - btc39-net
  ms-pasivocuentacorriente:
    build: ./ms_pasivocuentacorriente
    container_name: ms-pasivocuentacorriente
    ports:
      - "8085:8085"
    links:
      - mongodbcontainer
    depends_on:
      - ms-configserver
      - ms-discoveryserver
      - ms-client
      - ms-product
      - mongodbcontainer
    networks:
      - btc39-net
  ms-pasivoplazofijo:
    build: ./ms_pasivoplazofijo
    container_name: ms-pasivoplazofijo
    ports:
      - "8086:8086"
    links:
      - mongodbcontainer
    depends_on:
      - ms-configserver
      - ms-discoveryserver
      - ms-client
      - ms-product
      - mongodbcontainer
    networks:
      - btc39-net
  ms-activopersonal:
    build: ./ms_activopersonal
    container_name: ms-activopersonal
    ports:
      - "8087:8087"
    links:
      - mongodbcontainer
    depends_on:
      - ms-configserver
      - ms-discoveryserver
      - ms-client
      - ms-product
      - mongodbcontainer
    networks:
      - btc39-net
  ms-activoempresarial:
    build: ./ms_activoempresarial
    container_name: ms-activoempresarial
    ports:
      - "8088:8088"
    links:
      - mongodbcontainer
    depends_on:
      - ms-configserver
      - ms-discoveryserver
      - ms-client
      - ms-product
      - mongodbcontainer
    networks:
      - btc39-net
  ms-tarjetacredito:
    build: ./ms_tarjetacredito
    container_name: ms-tarjetacredito
    ports:
      - "8089:8089"
    links:
      - mongodbcontainer
    depends_on:
      - ms-configserver
      - ms-discoveryserver
      - ms-client
      - ms-product
      - mongodbcontainer
    networks:
      - btc39-net
networks:
  btc39-net:
    driver: bridge