version: "3.9"
services:
  mongodbcontainer:
    image: mongo:latest
    container_name: mongodbcontainer
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpwd
    ports:
      - 27018:27017
    restart: always
    logging:
      options:
        max-size: 1g
    networks:
      - some-net
  ms-configserver:
    build: ./ms_configserver
    container_name: ms-configserver
    ports:
      - "8888:8888"
    networks:
      - some-net
  ms-discoveryserver:
    build: ./ms_discoveryserver
    container_name: ms-discoveryserver
    ports:
      - "8761:8761"
    networks:
      - some-net
  ms-product:
    build: ./ms_product
    container_name: ms-product
    ports:
      - "8081:8081"
    links:
      - mongodbcontainer
    depends_on:
      - ms-configserver
      - ms-discoveryserver
      - mongodbcontainer
    networks:
      - some-net
networks:
  some-net:
    driver: bridge